# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_genome',
                'doc_host': 'https://dbikard.github.io',
                'git_url': 'https://github.com/dbikard/nbdev_genome',
                'lib_path': 'nbdev_genome'},
  'syms': {'nbdev_genome.core': {'nbdev_genome.core.foo': ('core.html#foo', 'nbdev_genome/core.py')}}}
