name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install optinal dependencies
        run: pip install -r optional_dependency.txt
      - uses: fastai/workflows/nbdev-ci@master
